version: "3.7"
services:
  app:
    build: ./
    links:
      - db
    ports:
      - "3000:3000"
  db:
    build: ./DB
    restart: always
    environment:
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306