version: "3.7"
services:
  app:
    build: ./
    links:
      - db
    ports:
      - "3000:3000"
  db:
    image: mysql:3.8
    restart: always
    environment:
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 32000:3306
    volumes:
      - ./DB:/docker-entrypoint-initdb.d/:ro